### ISSUE TITLE
Allow other tests to run when a test fails

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#835] opened 2019-07-13 00:10 UTC
Currently, `cargo miri test` will bail out on the first test that fails. This can make it very difficult to run Miri on a project's test suite - especially when the use of FFI/panicking is pervasive.

**Comment by RalfJung** [comment] 2019-07-13 07:35
Well, you are working on the panicking problem. ;)

I don't see a good way to continue execution on an interpreter error though.

**Comment by RalfJung** [comment] 2019-07-13 12:45
Actually I would say this is basically a duplicate of https://github.com/rust-lang/miri/issues/788. Please reopen if you disagree.

**Closed by RalfJung** 2019-07-13 12:45 UTC
Labels: A-engine, C-proposal
