### ISSUE TITLE
Miri looking for the cdylib which doesn't exist in the target dir

### ISSUE THREAD

**Issue by vertexclique** [rust-lang/miri#1627] opened 2020-11-16 14:00 UTC
After #1567 closed, I wanted to reenable MIRI today on production. Here is what came out of it:
```
error: extern location for jsonpath_lib does not exist: /home/runner/work/project/project/target/x86_64-unknown-linux-gnu/debug/deps/libjsonpath_lib-22ec0e5395ecf0cf.rmeta
 --> project/tests/util/project.rs:6:9
  |
6 |     use jsonpath_lib as jsonpath;
```
x86_64, linux, gnu

**Comment by RalfJung** [comment] 2020-11-16 14:55
Convincing cargo to do a check-only build "below its radar" seems to be really tricky. :/

Do you have a self-contained example that can be used to reproduce this problem?

**Comment by vertexclique** [comment] 2020-11-16 15:49
I will try to nail an MCVE.

**Comment by RalfJung** [comment] 2020-12-30 17:09
> I will try to nail an MCVE.

@vertexclique any progress on this?

**Comment by RalfJung** [comment] 2021-01-23 11:56
The current status of this issue is that I have no idea if it still exists, and there is no reproducible example. I am inclined to close it since in its current form, it is not actionable.

**Closed** 2021-01-23 12:05 UTC
Labels: A-cargo, C-bug
