### ISSUE TITLE
Function pointer provenance

### ISSUE THREAD

**Issue by VorfeedCanal** [rust-lang/miri#2926] opened 2023-06-13 20:19 UTC
I'm trying to pack bunch of function pointers to save memory and [have hit strange issue](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9b01323ef3138e717521af2373137d35):

```rust
fn foo(x: i32) -> i32 {
    x * 2
}

pub fn main() {
    let foo_addr: usize = unsafe {
        std::mem::transmute::<fn(x:i32)->i32, usize>(foo)
    };
    let foo_restored: fn(x:i32)->i32 = unsafe {
        std::mem::transmute::<usize, fn(x:i32)->i32>(foo_addr)
    };
    println!("{}", foo_restored(2));
}
```

Here Miri complains: `error: Undefined Behavior: out-of-bounds pointer use: 0x2794b[noalloc] is a dangling pointer (it has no provenance)`.

But [fn](https://doc.rust-lang.org/core/primitive.fn.html) doesn't have `with_addr` or anything similar. And it's not clear if it even should have it: at least in my case all functions are coming from the binary and thus all functions pointers are `'static` pointers… am I wrong? Should function pointers have provenance or not?

I'm just not sure what's the actual rules here and how to fix the issue.

**Comment by saethlin** [comment] 2023-06-13 21:07
It's not clear if function pointers have provenance. So nobody is really sure what the rules are. However...

> all functions are coming from the binary and thus all functions pointers are `'static` pointers… am I wrong?

Yes. The fact that the functions are "in the binary" is irrelevant. You are trying to use an observation about a representation that Rust can be lowered to in order to make an argument about Rust. Similarly, lifetime is also irrelevant. Pointers to `static`s still require provenance to be dereferenced.

The reason that it's unclear if function pointers should have provenance or not is that it's not clear if giving function pointers provenance permits any useful optimizations; the properties of an executable have nothing to do with it.

---

If you transmute to `*const ()` instead of `usize`, the code works fine, because the typed copy into the `*const ()` (or really any pointer type, but `*const ()` is the usual choice for an "I don't care" pointee type) does not carry the provenance.

If you really need pass this around as a `usize` (which I would advise against, but the choice is yours) you can use expose semantics. So:

```rust
fn foo(x: i32) -> i32 {
    x * 2
}

pub fn main() {
    let foo_addr: *const () = unsafe {
        std::mem::transmute::<fn(x:i32)->i32, *const ()>(foo)
    };

    let exposed = foo_addr as usize;

    let unexposed = exposed as *const ();

    let foo_restored: fn(x:i32)->i32 = unsafe {
        std::mem::transmute::<*const (), fn(x:i32)->i32>(unexposed)
    };
    println!("{}", foo_restored(2));
}
```

**Comment by RalfJung** [comment] 2023-06-14 07:55
Yeah, the recommended way to handle function pointers is to always transmute to/from raw pointers, and then use raw pointer APIs from there on.

**Comment by VorfeedCanal** [comment] 2023-06-14 20:35
> If you really need pass this around as a usize (which I would advise against, but the choice is yours) you can use expose semantics.

It's not as if I want to convert function pointer to `usize` variable for the sake of it.

I just have bunch of functions which receive `u8` slices and want to put them into one array: pointer to function, slice of data for that function, pointer to function, slice of data for that function and so on.

It's easily doable in Rust without Miri, but I don't know how to do that with Miri.

I tried to change your code just a tiny bit and it [gives warnings](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=24f73dff6bcd0fbe2e41fc04bd11d338):
```
fn foo(x: i32) -> i32 {
    x * 2
}

pub fn main() {
    let foo_addr: *const () = unsafe {
        std::mem::transmute::<fn(x:i32)->i32, *const ()>(foo)
    };

    let packed = (foo_addr as usize ^ 1).to_ne_bytes();

    println!("{packed:?}");

    let exposed = usize::from_ne_bytes(packed) ^ 1;

    let unexposed = exposed as *const ();

    let foo_restored: fn(x:i32)->i32 = unsafe {
        std::mem::transmute::<*const (), fn(x:i32)->i32>(unexposed)
    };
    println!("{}", foo_restored(2));
}
```

And if I try to add provenance [it no longer works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=77ff32a123cdc62271f6f29f2201449b):
```
#![feature(strict_provenance)]

fn foo(x: i32) -> i32 {
    x * 2
}

fn bar() -> () {
}


pub fn main() {
    let foo_addr: *const () = unsafe {
        std::mem::transmute::<fn(x:i32)->i32, *const ()>(foo)
    };

    let packed = (foo_addr as usize ^ 1).to_ne_bytes();

    println!("{packed:?}");

    let exposed = usize::from_ne_bytes(packed) ^ 1;

    let bar_addr: *const () = unsafe {
        std::mem::transmute::<fn()->(), *const ()>(bar)
    };

    let unexposed = bar_addr.with_addr(exposed);

    let foo_restored: fn(x:i32)->i32 = unsafe {
        std::mem::transmute::<*const (), fn(x:i32)->i32>(unexposed)
    };
    println!("{}", foo_restored(2));
}
```

**Comment by RalfJung** [comment] 2023-06-14 20:38
> And if I try to add provenance [it no longer works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=77ff32a123cdc62271f6f29f2201449b):

Yeah, you are using `bar`'s provenance with `foo`'s address, that is wrong, so Miri complains.

**Comment by RalfJung** [comment] 2023-06-14 20:43
> I just have bunch of functions which receive u8 slices and want to put them into one array: pointer to function, slice of data for that function, pointer to function, slice of data for that function and so on.

Due to provenance, `u8` is *not* a "universal type that can hold all initialized bytes". Using `u8` loses provenance. If you must use `u8`, and doing `ptr as usize`/`usize as ptr` casts is your only choice, and you will have to silence the Miri warning.

The way to avoid this loss of provenance is to use a different type, such as `MaybeUninit<u8>`, which can hold provenance. `MaybeUninit<u8>` is indeed a universal "byte" type that can hold all values a byte can have in Rust.

**Comment by khimru** [comment] 2023-06-14 21:29
> If you must use `u8`, then doing `ptr as usize`/`usize as ptr` casts is your only choice, and you will have to silence the Miri warning.

That's what I have already did. As you can guess I don't have tons of these casts spread around, there are just one function which adds function plus slice to the buffer and another which pulls it out and calls it.

I just added hashmap from address of function to function and miri is obviously happy. Just looked a bit silly for me to do all that dance with provenance for an object which is not ever allocated or deallocated thus I decided to ask here.

But given then fact that I'm doing that for yet-another-JIT… I guess having provenance for functions **is** important. I just wish all statically allocated functions had the same provevance: they couldn't ever be allocated or deallocated, why would **these** need provenance? But then, one may argue that the same idea may be applicable to any `&'static` reference thus it's no longer about functions.

But I guess that's low-priority issue. Thanks for the answers.

**Comment by VorfeedCanal** [comment] 2023-06-14 21:30
> If you must use `u8`, then doing `ptr as usize`/`usize as ptr` casts is your only choice, and you will have to silence the Miri warning.

That's what I have already did. As you can guess I don't have tons of these casts spread around, there are just one function which adds function plus slice to the buffer and another which pulls it out and calls it.

I just added hashmap from address of function to function and miri is obviously happy. Just looked a bit silly for me to do all that dance with provenance for an object which is not ever allocated or deallocated thus I decided to ask here.

But given then fact that I'm doing that for yet-another-JIT… I guess having provenance for functions **is** important. I just wish all statically allocated functions had the same provevance: they couldn't ever be allocated or deallocated, why would **these** need provenance? But then, one may argue that the same idea may be applicable to any `&'static` reference thus it's no longer about functions.

But I guess that's low-priority issue. Thanks for the answers.

**Comment by RalfJung** [comment] 2023-06-15 07:59
Closing as "Miri behaves as intended"; https://github.com/rust-lang/unsafe-code-guidelines/issues/340 is where we track whether function pointers should have provenance at all.

**Closed by RalfJung** 2023-06-15 07:59 UTC
