### ISSUE TITLE
ptr::swap_nonoverlapping can no longer copy pointers bytewise in latest miri 

### ISSUE THREAD

**Issue by tower120** [rust-lang/miri#2118] opened 2022-05-13 16:02 UTC
After updating miri from pre-1.60 to 1.62, I start getting those errors:
https://github.com/tower120/any_vec/runs/6425015915?check_suite_focus=true
(that branch runs OK with older MIRI)

Previously, miri had troubles with any raw pointer deference operations, for me. 
But I "fixed" that with `ptr::copy_nonoverlapping` - and it worked for miri.
It looks like there was some support for `std::ptr::*` operations on miri side... Which is now gone...

**Comment by RalfJung** [comment] 2022-05-13 16:09
Looks like you are using the 2022-04-04 nightly, which is quite old. We had some trouble with copy_nonoverlapping a few weeks ago, but that has since been fixed.

Can you try again with the latest nightly?

**Comment by RalfJung** [comment] 2022-05-13 16:11
Or maybe I looked into the wrong parts of the log? But this looks a lot like https://github.com/rust-lang/rust/issues/94371...

Do you have a self-contained example to reproduce the problem? That would help with debugging.

**Comment by tower120** [comment] 2022-05-13 16:15
>Can you try again with the latest nightly?

I'm not very good with rustup, but aren't it says 2022-05-11?
```
nightly-x86_64-unknown-linux-gnu installed - rustc 1.62.0-nightly (6dd68402c 2022-05-11)
```
https://github.com/tower120/any_vec/runs/6425015915?check_suite_focus=true#step:3:35

On my local Windows machine I can't install latest nightly, because it missing MIRI.

**Comment by tower120** [comment] 2022-05-13 16:16
> copy_nonoverlapping is definitely still supported, but you cannot use it to copy a part of a pointer -- you have to copy the entire thing in one go...

It does copy entire element with alignment, but represented as u8 byte array.

**Comment by tower120** [comment] 2022-05-13 16:21
Here is working branch https://github.com/tower120/any_vec/blob/exp_drop_after_remove

MIRI problem occurs here:
https://github.com/tower120/any_vec/blob/exp_drop_after_remove/src/lib.rs#L462

I don't have smaller example at hand now.

**Comment by RalfJung** [comment] 2022-05-13 16:43
That's a lot of code, I won't really have time to dig into that I am afraid. :/

(FWIW, it is a bad idea to represent pointers as a `u8` array. `u8` as an integer type does not carry [provenance](https://doc.rust-lang.org/nightly/core/ptr/index.html#strict-provenance). The recommended type to represent data of arbitrary type is `MaybeUninit<_>`. But that will probably not make a difference here.)

**Comment by tower120** [comment] 2022-05-13 16:44
Hmm, I tried to replace swap with 3 `ptr::copy_nonoverlapping` and intermediate vec and it worked!

```rust 
// same as copy_bytes but for swap_nonoverlapping.
#[inline]
unsafe fn swap_bytes(src: *mut u8, dst: *mut u8, count: usize){
    // MIRI hack
    if cfg!(miri) {
        let mut tmp = Vec::<u8>::new();
        tmp.resize(count, 0);
    
        // src -> tmp
        ptr::copy_nonoverlapping(src, tmp.as_mut_ptr(), count);
        // dst -> src
        ptr::copy_nonoverlapping(dst, src, count);
        // tmp -> dst
        ptr::copy_nonoverlapping(tmp.as_ptr(), dst, count);
    
        return;
    }

    // this does not work with MIRI
    // "unable to turn pointer into raw bytes"
    for i in 0..count{
        let src_pos = src.add(i);
        let dst_pos = dst.add(i);

        let tmp = *src_pos;
        *src_pos = *dst_pos;
        *dst_pos = tmp;
    }
}
```

The thing is
```rust
ptr::swap_nonoverlapping(src, dst, count);
```
does not work...

**Comment by RalfJung** [comment] 2022-05-13 16:45
Btw:
```
// This is faster then ptr::copy_nonoverlapping,
// when count is runtime value, and count is small.
```
That sounds like a bug worth reporting against rustc; a naive manual impl should not be faster than the stdlib method.

**Comment by tower120** [comment] 2022-05-13 16:52
> The recommended type to represent data of arbitrary type is MaybeUninit<_>. But that will probably not make a difference here.)

What about type-erased data?

**Comment by RalfJung** [comment] 2022-05-13 19:06
That's what I mean -- the correct type to store type-erased data in Rust is an array of `MaybeUninit<u8>`.

A `u8` (a) has to be initialized, and (b) cannot be a part of a pointer ("byte with provenance").

**Comment by RalfJung** [comment] 2022-05-13 19:09
Looking at the implementation of `swap_nonoverlapping`, this is indeed not surprising: it just copies the data one `T` at a time. Your `T` is `u8`, so this copies the pointers byte-per-byte, and Miri does not support this.

swap_nonoverlapping used to be implemented in a different way, that's why you didn't see these problems before.

I wonder if this is even a correct implementation, since it means this is a typed copy...

**Comment by tower120** [comment] 2022-05-13 19:40
If you found the problem - you don't need that branch anymore?

**Comment by RalfJung** [comment] 2022-05-13 20:52
I added a comment in https://github.com/rust-lang/rust/issues/63159#issuecomment-1126493271 to further discuss this.

For now, you can work around the problem by using `swap` rather than `swap_nonoverlapping`.

**Comment by RalfJung** [comment] 2022-05-13 21:01
Oh, but `swap` doesn't take a parameter to do this N times... your work-around with 3 ptr::copy_nonoverlapping is probably the best option for now then.

**Comment by RalfJung** [comment] 2022-06-03 12:19
Closing this in favor of https://github.com/rust-lang/miri/issues/2181.

**Closed by RalfJung** 2022-06-03 12:19 UTC
