### ISSUE TITLE
ICE: `thread 'rustc' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5`

### ISSUE THREAD

**Issue by clubby789** [rust-lang/miri#2445] opened 2022-07-25 19:42 UTC
This occured in https://github.com/clubby789/iced/commit/d7135a19dda56568b37ddb97e9bae25a106b754c, running `cargo miri test --features code_asm,mvex --release` in `src/rust/iced_x86`.

Traceback is at https://pastebin.com/Pc4AUpmd

@saethlin

**Comment by RalfJung** [comment] 2022-07-25 20:42
That sounds like we ran out of memory...
Is this on a 32bit system? 'capacity overflow' is not something I'd ever expect to see on a 64bit system.

**Comment by Nilstrieb** [comment] 2022-07-25 20:45
`iced`, when compiled using the relevant feature flags, has over 26k tests. This is probably causing some exponential SB blowup in libtest.

**Comment by Nilstrieb** [comment] 2022-07-25 20:58
(Note that running this command in miri also also _extremely_ slow, taking up to 15 minutes before the first test is even executed)

**Comment by saethlin** [comment] 2022-07-25 20:58
There is definitely some kind of algorithmic blowup happening. Is there somewhere better to share flamegraphs? I'm uploading them here gzipped so that GitHub doesn't strip the JavaScript out of them.
[flamegraph.svg.gz](https://github.com/rust-lang/miri/files/9184721/flamegraph.svg.gz)
[rustc.svg.gz](https://github.com/rust-lang/miri/files/9184722/rustc.svg.gz)
The measureme flamegraph seems rather confused

**Comment by RalfJung** [comment] 2022-08-04 21:10
@Nilstrieb do you know if this was using a 32bit or 64bit build of Miri?

I don't think this is very actionable -- it is probably an instance of "Stacked Borrows is slow (and consumes lots of memory)".

**Comment by saethlin** [comment] 2022-08-04 21:29
I feel like the only plausible explanation for this is a 32 bit interpreter.

I'm going to eventually tackle the startup time/memory usage issue in libtest, starting here: https://github.com/rust-lang/rust/pull/99939

I think it would be fair to close this as not planned?

**Comment by RalfJung** [comment] 2022-08-04 21:38
Agreed, closing as duplicate of https://github.com/rust-lang/miri/issues/1367.

**Closed by RalfJung** 2022-08-04 21:38 UTC
