### ISSUE TITLE
`cargo miri test` does not run doc-tests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#584] opened 2018-12-21 08:36 UTC
I am not sure what it would take to also make it build and execute doc-tests.  Probably just some tweaks in how we wrap `cargo rustc`?

**Comment by bjorn3** [comment] 2018-12-21 11:11
Doc tests need rustdoc as driver, while miri needs itself as driver.

**Comment by SimonSapin** [comment] 2019-07-16 16:59
@rust-lang/rustdoc, can rustdoc be used as a library (not a driver) to extract the doctests without running them?

**Comment by RalfJung** [comment] 2019-07-16 17:07
Or, alternatively, can we set some environment variable to make rustdoc call miri instead of rustc on each test after extraction?

**Comment by QuietMisdreavus** [comment] 2019-07-16 17:11
> @rust-lang/rustdoc, can rustdoc be used as a library (not a driver) to extract the doctests without running them?

Unfortunately, librustdoc was taken out of the sysroot a while back, and i don't think we auto-publish the source for that as a crate either, so there's not really an easy solution for that. Rustdoc itself doesn't really provide functionality to only save off the extracted/converted doctest, either.

> Or, alternatively, can we set some environment variable to make rustdoc call miri instead of calling rustc and running the binary on each test after extraction?

Same response - unless the test is manually marked as `ignore` (or given some non-rust language string) in the source, rustdoc will always run the converted doctest through rustc via the `librustc_interface` interface. There's an open PR to run the *compiled binaries* through a "test runner", but it doesn't sound like that will help either.

**Comment by RalfJung** [comment] 2019-07-16 17:14
How open would the rustdoc team be to provide a way for Miri to run the extracted tests, and what would be the preferred way of achieving that (librustdoc vs controlling what happens after extraction)?

For me it seems like the second option is the simpler one.

**Comment by bjorn3** [comment] 2019-07-16 17:16
The compilation of tests seems to be performed at https://github.com/rust-lang/rust/blob/17e62f77f954bed97aae839624bfd6dd68342daf/src/librustdoc/test.rs#L181.

**Comment by RalfJung** [comment] 2019-07-16 17:19
Yeah, now I see what @QuietMisdreavus meant by `librustc_interface` -- it does not call the rustc binary, it calls the rustc library.

The "easiest" way to get Miri into this would be to provide a way to call some binary *instead*, but I am not sure if that is feasible.

**Comment by QuietMisdreavus** [comment] 2019-07-16 17:22
If there were some flag we could provide to just save off all the doctests as standalone rust files, would that be enough to allow miri to attempt to build them? They're meant to be compiled as binaries and link against the regular crate and its dependency tree.

**Comment by RalfJung** [comment] 2019-07-16 17:23
> If there were some flag we could provide to just save off all the doctests as standalone rust files, would that be enough to allow miri to attempt to build them?

I guess we could make `cargo miri test` pick them up and run them all through Miri. The hard part would be to figure out the right command-line flags to get all the dependencies to work, but I am not sure if rustdoc can even help there?

**Comment by QuietMisdreavus** [comment] 2019-07-16 17:31
Cargo hands rustdoc all the `--extern` flags it needs when running `rustdoc --test` from `cargo test`, so presumably that information would be present in the crate's metadata.

**Comment by RalfJung** [comment] 2019-07-16 17:35
Hm, that raises the interesting question how `cargo miri test` would invoke rustdoc. Probably through `cargo test`? Can we do that targeting just the doctests of a particular binary?

Currently I wouldn't know how `cargo miri test` can get those flags; for the binaries we run we get them from `cargo` as well (`cargo miri` sets itself into the `RUSTC` env var so that `cargo` calls it with all the right flags and it just has to forward them).

**Comment by nox** [comment] 2019-08-02 17:08
Does `rustdoc` reads `RUSTC`? If so, could we make `miri` compile a small executable that runs the test under `miri` indirectly so that the changes to `rustdoc` are minimal?

**Comment by RalfJung** [comment] 2019-08-02 17:09
AFAIK rustdoc uses the rustc driver interface directly, it does not run a binary.

**Comment by nox** [comment] 2019-08-02 17:10
Oh right, I actually read that earlier in the thread today, but forgot about it now that it's Friday evening… My bad.

**Comment by RalfJung** [comment] 2019-08-30 20:18
With https://github.com/rust-lang/rust/pull/63827, rustdoc now runs rustc out-of-process. That should make it easier to run Miri instead.

@andjo403 is there a way to use an env var or so to control the binary that is run?

**Comment by andjo403** [comment] 2019-08-30 20:22
not yet working on a new PR where RUSTC env var can be set but have some test to fix

**Comment by WaffleLapkin** [comment] 2020-03-20 16:29
Is it possible now to somehow trick miri to run doctests?

**Comment by RalfJung** [comment] 2020-03-20 16:50
`rustdoc` probably lets us do that these days, but things have not been wired up in Miri yet.

**Comment by teryror** [comment] 2021-01-10 11:57
Is anyone actively working on this?

I'd be willing to invest a couple of afternoons over the coming week or two, but I could definitely use some pointers on how to get started. I never touched any of the involved projects before. I did read the contributor's guide, though.

Based on what's been said here and what I gathered from reading code, this would basically boil down to replacing [this error message](https://github.com/rust-lang/miri/blob/a09f8b0c06c6bb051bd1e104c6be56fbe51f3d86/cargo-miri/bin.rs#L769) with a call to a new function `phase_cargo_rustdoc`, pretty much without changing anything else. I that assessment correct?

The problem is I'm not clear on what that function should do exactly. Invoke `rustdoc --test --test-builder {?}`, then the executable that produces, presumably?

**Comment by RalfJung** [comment] 2021-01-10 16:46
> Is anyone actively working on this?

No, not that I know of.

> I'd be willing to invest a couple of afternoons over the coming week or two, but I could definitely use some pointers on how to get started. I never touched any of the involved projects before. I did read the contributor's guide, though.

That's great. :) However, I'm afraid there's not a ton of guidance available on this issue -- part of the problem here is even figuring out how to best do this.

> Based on what's been said here and what I gathered from reading code, this would basically boil down to replacing this error message with a call to a new function phase_cargo_rustdoc, pretty much without changing anything else. Is that assessment correct?

Yes, that sounds right.

> The problem is I'm not clear on what that function should do exactly. Invoke rustdoc --test --test-builder {?}, then the executable that produces, presumably?

I don't know either what exactly it should do. ;) Probably the first step is to figure out the interaction between rustdoc and cargo, which is the thing that we are "hooking" here. Does cargo call rustdoc to build some binaries, and then the binaries are run by cargo, or does cargo run rustdoc and rustdoc runs some binaries? What kind of command-line arguments does cargo pass to rustdoc, and does Miri have to patch them in any way (besides adding `--test-builder`)? There will be some exploration and research needed to figure this out, and indeed that exploration and research is the largest part of the work that needs to be done to resolve this issue.

**Comment by teryror** [comment] 2021-01-10 16:54
Alright. I've skimmed what seemed to be the relevant parts of cargo, I guess I'll have to take a closer look then.

Thanks for the guiding questions, that's already pretty helpful!

**Comment by RalfJung** [comment] 2021-01-10 17:04
Awesome. :) Don't hesitate to ask if you have further questions. (But also, I might not always be able to answer so quickly, so when delays happen that's just because I am busy.)

Judging from `--test-builder`, I *think* rustdoc is only building binaries, not running them. So likely Miri should make rustdoc invoke miri as the builder and make sure that this rustdoc-invoked Miri enters `phase_cargo_rustc`. Assuming this is always a binary crate, this would make Miri emit a JSON file as the "binary" with all the required information that is needed later when cargo tells Miri to "run" that JSON file.

**Comment by teryror** [comment] 2021-01-11 14:13
Status report!

I spent some time reading the source to `librustdoc`, and it looks to me like you were mistaken. After spawning a `test_builder` process to produce an `output_file`, rustdoc tries to execute it. However, it also has the `--runtool` and `--runtool-arg` options. If a run tool is provided, it invokes

    $runtool ($runtool-arg)* $output_file

instead. The run tool should be the driver `miri`, rather than `cargo-miri`, correct? Under that assumption, here's a naive draft:

```rust
fn phase_cargo_rustdoc(args: env::Args) {
    let verbose = std::env::var_os("MIRI_VERBOSE").is_some();

    // phase_cargo_miri sets the RUSTDOC env var to ourselves, so we can't use that here;
    // just default to a straight-forward invocation for now:
    let mut cmd = Command::new(OsString::from("rustdoc"));
    cmd.args(args); // just pass everything through until we find a reason not to do that

    // Use our custom sysroot -- I'm *guessing* this is required
    let sysroot =
        env::var_os("MIRI_SYSROOT").expect("the wrapper should have set MIRI_SYSROOT");
    cmd.arg("--sysroot").arg(sysroot);

    cmd.arg("-Z").arg("unstable-options");
    let cargo_miri_path = std::env::current_exe().expect("current executable path invalid");
    cmd.arg("--test-builder").arg(cargo_miri_path);

    cmd.arg("--runtool").arg(find_miri());
    // any additional arguments that need to be passed to miri go here, each one prefixed by `--runtool-arg`
    // not sure if any are required?

    if verbose {
        eprintln!("[cargo-miri rustdoc] {:?}", cmd);
    }

    exec(cmd)
}
```

I can't test this quite yet, because the `--test-builder` option [appears to be broken](https://github.com/rust-lang/rust/issues/80893). I'll try forking the rust repo later today so I might give this a shot. I was still hoping I wouldn't have to do that, but c'est la vie.

**Comment by RalfJung** [comment] 2021-01-12 12:41
> I spent some time reading the source to librustdoc, and it looks to me like you were mistaken. After spawning a test_builder process to produce an output_file, rustdoc tries to execute it. However, it also has the --runtool and --runtool-arg options.

Ah, interesting -- good find.
This will mean more work for you.^^ Yes, the runtool will have to be Miri, but it will need all the arguments that were passed to `--test-builder`. That's the same issue as with regular cargo builds and running them; it's why the builds create JSON files -- then when running them we have all the aguments available that were passed for the build.

> The way rustdoc invokes the test builder is indistinguishable from the way cargo invokes rustdoc, at least from the command line arguments. It does, however, set some UNSTABLE_ environment variables we can check for. Not a great thing to depend on, but it'll do, I suppose. 

Well, `phase_cargo_rustc` could set an env var, wouldn't that help?

> The issue I'm facing now is that rustdoc passes the generated code to rustc via stdin, rather than a temporary file. I can't think of a simple way to trick cargo-miri into just dealing with that.

Ugh. Yes that will be interesting.^^

> Does the miri driver support piping code in like that? If so, I could make phase_cargo_rustc record the contents of stdin in the temporary JSON file, and make phase_cargo_runner play them back, so to speak. Alternatively, I could add two more phases, phase_rustdoc_rustc and phase_rustdoc_runner, respectively.

Miri uses rustc for input file handling, so stdin *should* just work. It has never been tested though.
I'd prefer reusing existing code as much as possible, i.e., `phase_cargo_rustc` and `phase_cargo_runner` should coordinate to forward stdin when necessary. The tricky bit will be to not do this *always* but only when needed; in the "normal" case we'll sttil want to use the normal stdin for running Miri so that the interpreted program can read from stdin.

**Comment by bjorn3** [comment] 2021-01-12 12:48
> Ugh. Yes that will be interesting.^^

It also sets a few env vars to fixup the source location shown in error messages.

**Comment by teryror** [comment] 2021-01-12 15:28
> It also sets a few env vars to fixup the source location shown in error messages.

You mean `UNSTABLE_RUSTDOC_TEST_PATH` and `UNSTABLE_RUSTDOC_TEST_LINE`? That's what I'm checking for :)

> Well, `phase_cargo_rustdoc` could set an env var, wouldn't that help?

That would probably help in orchestrating the other phases, but I'm testing the `UNSTABLE_*` vars to see if I should call `phase_cargo_rustdoc` in the first place.

Say if `MIRI_CALLED_FROM_RUSTDOC` is set, `phase_cargo_rustc` reads all of stdin and dumps it into the JSON file, and `phase_cargo_runner` just needs to know about the optional field. Seems like a decent plan, no?

I'll give that a shot later today, but first I'll have to add a regression test to rustdoc to get my PR accepted :)

**Comment by RalfJung** [comment] 2021-01-12 16:37
> That would probably help in orchestrating the other phases, but I'm testing the UNSTABLE_* vars to see if I should call phase_cargo_rustdoc in the first place.

Why is that needed? This case distinction already exists in master (to emit the error message).

> Say if MIRI_CALLED_FROM_RUSTDOC is set, phase_cargo_rustc reads all of stdin and dumps it into the JSON file, and phase_cargo_runner just needs to know about the optional field. Seems like a decent plan, no?

Yes that works.

**Comment by teryror** [comment] 2021-01-12 17:07
> Why is that needed? This case distinction already exists in master (to emit the error message).

You're right, my mistake, I got confused for a second there. This should work perfectly fine then.

**Comment by teryror** [comment] 2021-01-12 21:29
I seem to have a mostly working prototype! See the full code [here](https://github.com/teryror/miri/blob/master/cargo-miri/bin.rs) and the diff [here](https://github.com/teryror/miri/commit/d1b7b0ccd034bbcbc70e9c0b438d5beec589a9a7).

`MIRI_VERBOSE` output is swallowed for passing tests, of course, but purposefully failing one shows that `phase_cargo_rustc` and `phase_cargo_runner` are indeed called appropriately, and the test output matches my expectation. Miri seems to be dealing with piped input just fine.

Problem is that `compile_fail` tests all fail due to being erroneously accepted, I'm not sure why that is yet. I'll call it a day for now, though.

Should we continue this discussion on a draft PR?

**Comment by teryror** [comment] 2021-01-14 18:06
I got it to work! :tada:

I was missing an `--emit=dep-info,metadata` argument to the check-only build. The ICE still should be considered a bug, though, right?

I went ahead and opened a PR :D

**Comment by RalfJung** [comment] 2021-01-17 19:23
That's awesome. :) Thanks a lot for your work @teryror!

**Closed** 2021-04-06 09:00 UTC
Labels: A-cargo, C-enhancement

**Comment by LeonineKing1199** [comment] 2021-04-23 17:00
I'm having trouble getting Miri to ignore certain doctests. Namely, I have some doctests that use SIMD.

```rust
  /// # Example
  /// ```
  /// #[cfg_attr(miri, ignore)]
  /// fn main() {
```

The above doctest winds up getting run anyway. Is there any method used to ignore a doctest?

**Comment by RalfJung** [comment] 2021-04-23 17:14
I don't think `ignore` does anything for doctests.

Did you try `#[cfg(not(miri))]`?
