### ISSUE TITLE
macOS: cannot subtract Instants (mach_timebase_info not implemented)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1288] opened 2020-03-31 15:52 UTC
On macOS, we cannot subtract one `Instant` from another:
```
error: unsupported operation: can't call foreign function: mach_timebase_info
   --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/time.rs:239:13
    |
239 |             mach_timebase_info(&mut info);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: mach_timebase_info
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
    = note: inside call to `std::sys::unix::time::inner::info` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/time.rs:156:24
    = note: inside call to `std::sys::unix::time::inner::Instant::checked_sub_instant` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/time.rs:263:9
note: inside call to `std::time::Instant::duration_since` at tests/run-pass/time.rs:25:20
   --> tests/run-pass/time.rs:25:20
    |
25  |         let diff = now2.duration_since(now1);
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: inside call to `main` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/rt.rs:67:34
```

**Comment by samrat** [comment] 2020-04-13 10:12
I am unable to reproduce this on macOS `10.14.6`-- all tests pass when I run `./miri test` on commit 4545effb.

**Comment by RalfJung** [comment] 2020-04-13 10:19
@samrat yes they should pass, we have CI for that. :)
But this feature is not implemented yet, so far we also not testing it. If you want to test it locally, edit [this file](https://github.com/rust-lang/miri/blob/fbbd4428d0e771a9dc9adc98a150b410ba1b2b45/tests/run-pass/time.rs) to remove the `#[cfg(not(target_os = "macos"))]`, then run
```
./miri run tests/run-pass/time.rs -Zmiri-disable-isolation
```

**Comment by samrat** [comment] 2020-04-13 11:16
Ah, yes I am able to reproduce this now-- I thought it might have gotten fixed since this issue was created.

I am quite new to the miri codebase but I'll try to come up with a fix for this issue.

**Comment by RalfJung** [comment] 2020-04-13 11:30
Sure, let me know if you need any help. :)

**Closed** 2020-04-14 10:52 UTC
Labels: A-mac, A-shims, C-enhancement, E-easy
