### ISSUE TITLE
unsupported operation: can't call foreign function `posix_spawnattr_init` on OS `macos`

### ISSUE THREAD

**Issue by camelid** [rust-lang/miri#3728] opened 2024-07-02 23:48 UTC
This foreign function is used by `std::process::Command::status()`, so it seems like a common enough operation.

Flags: I of course ran with `-Zmiri-disable-isolation` since I'm doing I/O.

rustc version and arch info:

```
rustc 1.81.0-nightly (d0227c6a1 2024-06-11)
binary: rustc
commit-hash: d0227c6a19c2d6e8dceb87c7a2776dc2b10d2a04
commit-date: 2024-06-11
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

**Comment by saethlin** [comment] 2024-07-03 01:00
We should probably have a more detailed explanation of the path forward for these errors. Adding shims for the process-spawning functions is uninteresting until someone has a full plan for how to support subprocesses.

**Comment by RalfJung** [comment] 2024-07-03 06:28
This is effectively a duplicate of https://github.com/rust-lang/miri/issues/3374 -- we don't support `Command`.

**Closed by RalfJung** 2024-07-03 06:28 UTC
