### ISSUE TITLE
Compile hashbrown fails with unresolved import `crate::sys_common::backtrace`

### ISSUE THREAD

**Issue by That3Percent** [rust-lang/miri#950] opened 2019-09-13 16:22 UTC
This is my first time attempting to use miri via `cargo miri test` on one of my crates, [second-stack](https://github.com/That3Percent/second-stack). So, this may be a configuration issue and not necessarily a regression.

I'm using rust nightly 2019-09-13, compiling a crate with no external dependencies. When miri compiles hashbrown it fails with the following output...
```
   Compiling hashbrown v0.5.0
error[E0432]: unresolved import `crate::sys_common::backtrace`
  --> C:\Users\Zac\.rustup\toolchains\nightly-2019-09-13-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\backtrace.rs:98:24
   |
98 | use crate::sys_common::backtrace::{output_filename, lock};
   |                        ^^^^^^^^^ could not find `backtrace` in `sys_common`

```

**Comment by RalfJung** [comment] 2019-09-13 16:29
Thanks for the report!

This is a duplicate of https://github.com/rust-lang/rust/issues/64410: a recent libstd change broke building libstd with xargo.

Until that is resolved, I recommend using `nightly-2019-09-11` as your toolchain. That should work fine.

**Closed by RalfJung** 2019-09-13 16:29 UTC
