### ISSUE TITLE
Memory leak checker misses AtomicPtr

### ISSUE THREAD

**Issue by cynecx** [rust-lang/miri#1574] opened 2020-10-05 21:08 UTC
```rust
use std::{
    cell::UnsafeCell,
    ptr,
    sync::atomic::{AtomicPtr, Ordering},
};

fn leak() {
    static LEAK: AtomicPtr<usize> = AtomicPtr::new(ptr::null_mut());
    LEAK.store(Box::into_raw(Box::new(0usize)), Ordering::SeqCst);
}

fn no_leak() {
    struct Local(UnsafeCell<*mut usize>);

    unsafe impl Send for Local {}
    unsafe impl Sync for Local {}

    static LEAK: Local = Local(UnsafeCell::new(ptr::null_mut()));
    *unsafe { &mut *LEAK.0.get() } = Box::into_raw(Box::new(0usize));
}

fn main() {
    no_leak();
    // leak();
}
```

Miri considers memory leaks reachable through a static global as non-leaking. I'd expect the Atomic* case be non-leaking as well, however miri reports it as leaked memory.

```
The following memory was leaked: alloc1834 (Rust heap, size: 8, align: 8) {
    00 00 00 00 00 00 00 00                         │ ........
}

error: the evaluated program leaked memory

error: aborting due to previous error; 1 warning emitted
```

(This is a special case of https://github.com/rust-lang/miri/issues/1618.)

**Comment by bjorn3** [comment] 2020-10-05 21:20
`AtomicPtr` casts the pointer to an integer before storing it. This prevents miri from seeing that the `AtomicPtr` keeps it alive.

**Comment by oli-obk** [comment] 2020-10-06 07:11
So... we can either not do a cast in `AtomicPtr` (I guess a transmute will keep the provenance?) or we need to teach `AtomicPtr` to set the `miri_static_root` (but that would be overly permissive, as you could now also just do that in non-static code).

**Comment by RalfJung** [comment] 2020-10-06 07:12
Yeah, I cannot think of a good way to ix this I am afraid... we cannot just randomly cast any integer we see to a pointer in the off chance that it represents an actual address. Ideally `AtomicPtr` would not cast pointers to integers, but the underlying problem here is that LLVM does not support atomic operations on pointers.

Probably I should not have closed https://github.com/rust-lang/miri/issues/1318, which is the same problem. Crossbeam is also affected by this (https://github.com/crossbeam-rs/crossbeam/issues/464).

Currently the best way to approach the problem is to call [`miri_static_root`](https://github.com/rust-lang/miri#miri-extern-functions).

**Comment by oli-obk** [comment] 2020-10-06 07:16
>  I guess we could push this down to the LLVM codegen layer so that the Rust intrinsic does support pointers, not sure if that would be a good idea.

Oh, I like this. That seems entirely reasonable to me

**Comment by oli-obk** [comment] 2020-10-06 10:07
>  the underlying problem here is that LLVM does not support atomic operations on pointers

I was unable to find any recent information on this being true and changing it in rustc to just use pointers worked without any additional changes.

**Comment by oli-obk** [comment] 2020-10-06 10:07
>  the underlying problem here is that LLVM does not support atomic operations on pointers

I was unable to find any recent information on this being true and changing it in rustc to just use pointers worked without any additional changes.

**Comment by RalfJung** [comment] 2020-10-06 11:29
Uh I thought I had LLVM experts confirm that when I asked but maybe I misremember.

**Comment by RalfJung** [comment] 2020-11-02 09:19
FWIW, this is also a problem when using `-Zmiri-track-raw-pointers`, which breaks int-to-ptr casts -- both Windows in general, and accessing the program argument on Unix systems, involve `AtomicPtr` and thus fail with `-Zmiri-track-raw-pointers`.

**Comment by RalfJung** [comment] 2020-11-21 19:27
Status: @oli-obk started some work on supporting raw pointer types in the atomic intrinsics in https://github.com/rust-lang/rust/pull/77611, and then realized that this would need some support by the codegen backend since LLVM only supports atomic operations on integer types.

**Comment by jonhoo** [comment] 2022-02-28 00:57
Just to double-check my understanding; is it expected that `-Zmiri-track-raw-pointers` will fail to track correctly when using `AtomicPtr::compare_exchange` and friends, since they still use pointers-as-integers under the hood (I think only load/store (https://github.com/rust-lang/rust/pull/77611) and swap (https://github.com/rust-lang/rust/pull/80236) have been "fixed")?

**Comment by oli-obk** [comment] 2022-02-28 07:17
Yes. We need to fix this in libstd/rustc, miri is doing the right thing ™️ and implementing workarounds just on the miri side is not feasible afaict

**Comment by RalfJung** [comment] 2022-03-01 14:33
So looks like [this comment](https://github.com/rust-lang/rust/pull/80236#discussion_r546401361) was not accurate then?
> If you have the time, could you remove all as *mut usize and as usize from the implementation of AtomicPtr and adjust the intrinsics accordingly?

 > I don't think there is anything left (though I might have missed something). Remaining operations are intentionally unsupported in atomic ptr, so I don't think we should support them in intrinsics either.

**Comment by RalfJung** [comment] 2022-03-01 22:10
@jonhoo looking at the `compare_exchange` implementation, it does not seem to use int-to-ptr casts:

https://github.com/rust-lang/rust/blob/1cc0ae4cbbcb9909035b5b99fc20bf6b79f4010c/library/core/src/sync/atomic.rs#L1153

So actually I think I disagree with Oli, this is not expected. Do you have a small example of this going wrong?

**Comment by RalfJung** [comment] 2022-03-02 13:36
Yes, that message indicates an int-to-ptr cast. But the question is where that cast is happening...

**Comment by RalfJung** [comment] 2022-03-02 13:37
Anyway, AtomicPtr is likely innocent, so I will re-close this issue. Can you open a new issue for this problem?

**Closed by RalfJung** 2022-03-02 13:37 UTC
Labels: C-enhancement, A-leaks

**Comment by jonhoo** [comment] 2022-03-02 14:54
Ugh, looking through the code again, I realized that I *do* cast between pointers and integers to manage a bit in a pointer as a lock. That's unfortunate, but explains the problem. Sorry for the noise!

Any news on whether Miri might gain capabilities for tracking pointers even in the presence of such casts and bit flips? Potentially with some extra code to tell Miri what's going on through an extern? These kinds of tricks are quite common in concurrency primitive libraries where Miri is invaluable.

**Comment by RalfJung** [comment] 2022-03-02 15:03
Please open a new issue with a pointer to the relevant code. Ö=

**Comment by jonhoo** [comment] 2022-03-02 16:01
Filed https://github.com/rust-lang/miri/issues/1993
