### ISSUE TITLE
can't call foreign function `CreateFileW` on OS `windows`

### ISSUE THREAD

**Issue by deadsoul44** [rust-lang/miri#3806] opened 2024-08-15 14:25 UTC
```
error: unsupported operation: can't call foreign function `CreateFileW` on OS `windows`
   --> C:\Users\ASUS\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\pal\windows\fs.rs:299:13
    |
299 | /             c::CreateFileW(
300 | |                 path.as_ptr(),
301 | |                 opts.get_access_mode()?,
302 | |                 opts.share_mode,
...   |
306 | |                 ptr::null_mut(),
307 | |             )
    | |_____________^ can't call foreign function `CreateFileW` on OS `windows`
    |
    = help: if this is a basic API commonly used on this target, please report an issue with Miri
```

**Comment by RalfJung** [comment] 2024-08-15 14:30
Thanks for the report!

This is a duplicate of https://github.com/rust-lang/miri/issues/3482.

**Closed by RalfJung** 2024-08-15 14:30 UTC
