### ISSUE TITLE
support for global C initializers

### ISSUE THREAD

**Issue by elichai** [rust-lang/miri#1171] opened 2020-02-11 12:25 UTC
Hi,
I'm not sure if rust even officially supports this (maybe should open an unsafe-guideline discussion?)
but basically you can initialize arrays by linking into the right place in elf/exe etc but miri doesn't run this
https://play.rust-lang.org/?gist=04058d55590a58168f916a0e273add42

FWIW c2rust uses this to initialize global statics.

**Comment by RalfJung** [comment] 2020-02-11 15:44
I think this is a duplicate of https://github.com/rust-lang/miri/issues/450 ?

**Closed** 2020-02-12 09:09 UTC
Labels: A-engine, A-shims, C-enhancement
