### ISSUE TITLE
Cannot run a miri test on a glommio application

### ISSUE THREAD

**Issue by tontinton** [rust-lang/miri#2834] opened 2023-04-06 21:08 UTC
Basically `glommio` runs some OS functions, like:

```
175 | /             libc::sched_setaffinity(
176 | |                 pid.into(),
177 | |                 mem::size_of::<CpuSet>() as libc::size_t,
178 | |                 &cpuset.cpu_set,
179 | |             )
    | |_____________^ can't call foreign function `sched_setaffinity` on OS `linux`
```

Is adding that a possibility? if it is, and you do have time, I'll gladly look into implementing this myself.

**Comment by bjorn3** [comment] 2023-04-06 21:18
Impelementing sched_setaffinity should be easy. It did just be a no-op. Implementing iouring on the other hand is a lot more complex. Especially because the intention is that user code and a kernel thread access the same linked list concurrently. While I think it would be valid to block on the completion of the entire list of commands before returning from the syscall that triggers running the commands, even this is already non-trivial and it may hide a decent amount of bugs.

**Comment by RalfJung** [comment] 2023-05-13 16:29
Duplicate of https://github.com/rust-lang/miri/issues/2749

**Closed by RalfJung** 2023-05-13 16:29 UTC
