### ISSUE TITLE
MaybeUninit+Cell results in constant evaluation error: Location is not frozen long enough

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/miri#615] opened 2019-02-07 10:21 UTC
The following code triggers an error in miri:
```rust
#![feature(maybe_uninit)]
use std::mem::MaybeUninit;
use std::cell::Cell;

fn main() {
    let x: MaybeUninit<(Cell<u32>, u32)> = MaybeUninit::uninitialized();
    x.as_ptr();
}
```
```
error[E0080]: constant evaluation error: Location is not frozen long enough
    --> /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem.rs:1141:20
     |
1141 |         unsafe { &*self.value as *const T }
     |                    ^^^^^^^^^^ Location is not frozen long enough
     |
note: inside call to `<std::mem::MaybeUninit<T>><(std::cell::Cell<u32>, u32)>::as_ptr` at src/main.rs:7:5
    --> src/main.rs:7:5
     |
7    |     x.as_ptr();
     |     ^^^^^^^^^^
     = note: inside call to `main` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:64:34
```

**Comment by RalfJung** [comment] 2019-02-07 12:04
Ah, I figured there'd be a Cell involved. :/

This gets "fixed" by implementing https://github.com/rust-lang/rfcs/pull/2582, but not really.

**Comment by RalfJung** [comment] 2019-02-08 13:27
This version of the problem is worse:
```rust
#![feature(maybe_uninit)]
use std::mem::MaybeUninit;
use std::cell::Cell;

fn main() {
    let mut x: MaybeUninit<(Cell<u32>, u32)> = MaybeUninit::uninitialized();
    x.set((Cell::new(0), 0));
    unsafe { x.get_ref(); }
}
```

**Comment by RalfJung** [comment] 2019-04-17 13:31
This will be fixed by https://github.com/rust-lang/miri/pull/695, I added the examples above as a test.

**Closed** 2019-04-18 08:15 UTC
Labels: A-stacked-borrows, C-bug
