### ISSUE TITLE
Error on test that should panic in num-complex

### ISSUE THREAD

**Issue by kennethbgoodin** [rust-lang/miri#770] opened 2019-06-13 18:21 UTC
Miri panics and fails when running a test marked with #[should_panic] in the `num-complex` crate.

The test in question:

```    #[test]
    #[should_panic]
    fn test_divide_by_zero_natural() {
        let n = Complex::new(2, 3);
        let d = Complex::new(0, 0);
        let _x = n / ```

Log: https://gist.github.com/kennethbgoodin/f648b0164557faaca30584fcc456605e

**Comment by bjorn3** [comment] 2019-06-13 18:23
Miri doesn't support unwinding yet. You may want to wait for https://github.com/rust-lang/miri/pull/693.

**Comment by kennethbgoodin** [comment] 2019-06-13 18:24
I figured as much, added the issue so I can reference it elsewhere.

**Comment by RalfJung** [comment] 2019-06-13 18:25
This is a duplicate of https://github.com/rust-lang/miri/issues/658.

**Comment by RalfJung** [comment] 2019-06-13 18:25
Oh, also, try
```
cargo miri test -- -- -Zunstable-options --exclude-should-panic
```
to skip those tests.

**Comment by kennethbgoodin** [comment] 2019-06-13 18:26
Oh thanks! That's helpful.

**Closed by RalfJung** 2019-06-13 18:25 UTC
