### ISSUE TITLE
Miri not detecting aliased mutable reference

### ISSUE THREAD

**Issue by Kestrer** [rust-lang/miri#1666] opened 2021-01-10 06:10 UTC
I think that this code contains UB:

```rust
fn use_mut(r: &mut i32) {
    *r += 1;
    let _ = &mut *r;
}

fn main() {
    let r = &mut 5;
    let p = r as *mut _;
    use_mut(r);
    use_mut(unsafe { &mut *p });
    use_mut(r);
}
```

But when running under Miri, no errors are produced.

**Comment by RalfJung** [comment] 2021-01-10 17:01
Interesting example, thanks for the report!

This is caused by the fact that the `r` that is passed to `use_mut` is a two-phase borrow. Miri treats two-phase borrows like raw pointers -- with the current version of Stacked Borrows, we cannot really do much better. Hopefully a future version of Stacked Borrows can restrict two-phase borrows better.

If you use `use_mut(&mut *r)` instead of `use_mut(r)`, "real" reborrows happen and you get the expected error.

**Comment by RalfJung** [comment] 2021-02-17 08:43
Closing in favor of https://github.com/rust-lang/unsafe-code-guidelines/issues/85.

**Closed by RalfJung** 2021-02-17 08:43 UTC
