### ISSUE TITLE
ICE on "cargo miri test"

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/miri#1795] opened 2021-05-13 21:42 UTC
```
error: internal compiler error: /rustc/952c5732c2d25a875f90e5cd5dd29a1a21c1d4a2/compiler/rustc_mir/src/interpret/place.rs:240:18: vtable not supported on type std::pin::Pin<&mut dyn std::future::Future<Output = ()> + std::marker::Send>

thread 'rustc' panicked at 'Box<Any>', /rustc/952c5732c2d25a875f90e5cd5dd29a1a21c1d4a2/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (952c5732c 2021-05-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error
```

**Comment by oli-obk** [comment] 2021-05-13 23:44
Do you have an example code that causes this or any hints for reproduction of the ICE?

**Comment by Keruspe** [comment] 2021-05-14 06:37
Happens with e.g. https://github.com/Keruspe/uexec/commit/575c3ed41c8dea50e795e163eb2250c3145cb9c1

Not sure how to extract a minimal reproducer

**Comment by RalfJung** [comment] 2021-05-14 07:00
From the looks of it I think this is a duplicate of https://github.com/rust-lang/miri/issues/1038.

**Comment by RalfJung** [comment] 2021-12-16 14:29
Closing as duplicate of https://github.com/rust-lang/miri/issues/1038.

**Closed by RalfJung** 2021-12-16 14:29 UTC
