### ISSUE TITLE
How to support or disable SIMD instructions?

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/miri#3274] opened 2024-01-23 11:19 UTC
I am currently trying to use `miri` to run the testsuite of my project. However, the [`wast`] dependency is problematic in that it uses SIMD operations even though I disabled all optimizations:
```
test spec::wasm_store ... error: unsupported operation: can't call foreign function `llvm.aarch64.neon.umaxp.v16i8` on OS `macos`
    --> /Users/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/aarch64/neon/mod.rs:1907:5
     |
1907 |     vpmaxq_u8_(a, b)
     |     ^^^^^^^^^^^^^^^^ can't call foreign function `llvm.aarch64.neon.umaxp.v16i8` on OS `macos`
     |
```
The instruction in question is this:
https://github.com/rust-lang/stdarch/blob/0215f9ac74170ef3a4b385c60fe35dfefceacf33/crates/core_arch/src/aarch64/neon/mod.rs#L254

Command used: `cargo +nightly miri test my_test -Z build-std --profile dev`

**Questions:**

- Is there any way I can configure Rust/LLVM/Cargo so that they do not produce instructions unsupported by `miri` such as SIMD instructions?
- What are the chances that `miri` supports SIMD instructions and thus supporting my use case?

[`wast`]: crates.io/crates/wast

Used Rust toolchain: `rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)`

**Comment by bjorn3** [comment] 2024-01-23 12:08
> Is there any way I can configure Rust/LLVM/Cargo so that they do not produce instructions unsupported by miri such as SIMD instructions?

No, if a dependency does not have a way to disable this, there is nothing that can be done other than adding support for the simd intrinsic to miri.

> What are the chances that miri supports SIMD instructions and thus supporting my use case?

For x86 a fair amount of simd intrinsics have been implemented somewhat recently (see https://github.com/rust-lang/miri/tree/master/src/shims/x86 for the full list). For any other architecture no simd intrinsics are supported at all.

**Comment by Robbepop** [comment] 2024-01-23 12:37
@bjorn3 thank you for the information!

I am running `miri` on `aarch64-apple-darwin` but the following command seems to work:
```
cargo +nightly miri test spec::wasm_store -Z build-std --profile dev --target x86_64-apple-darwin
```
Probably due to Rosetta.

**Comment by bjorn3** [comment] 2024-01-23 12:43
Miri actually natively supports cross-execution. It will happily run big endian powerpc-unknown-linux-gnu on an x86_64-pc-windows-msvc host. This works because with miri nothing actually gets compiled down to machine code. It interprets MIR instructions. Changing targets only changes the `#[cfg]`'s presented to user code as well as memory layout and the set of OS functions miri will emulate. Miri doesn't need a cpu capable of running programs written for the target, a linker for the target or any system libraries for the target.

**Comment by Robbepop** [comment] 2024-01-23 12:54
Ah that makes sense so actually using `--target x86_64-apple-darwin` was the right call to make `miri` work on my system and probably also when using `miri` in the CI.

I am now receiving the `miri` error about UB that I'd expect to see, although I am not sure if it is a false positive.
```
test spec::wasm_store ... error: Undefined Behavior: trying to retag from <6407251> for Unique permission at alloc1827492[0x0], but that tag only grants SharedReadOnly permission for this location
   --> /Users/robin/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:450:18
    |
450 |         unsafe { &mut *self.as_ptr() }
    |                  ^^^^^^^^^^^^^^^^^^^
    |                  |
    |                  trying to retag from <6407251> for Unique permission at alloc1827492[0x0], but that tag only grants SharedReadOnly permission for this location
    |                  this error occurs as part of retag at alloc1827492[0x0..0x10000]
```
I read this as `miri` denies access to a `*const T` because I wanted to read it as `*mut T`.
Looking into the definition of `NonNull<T>` I see the following: (https://doc.rust-lang.org/src/core/ptr/non_null.rs.html#72-74)
```rust
pub struct NonNull<T: ?Sized> {
    pointer: *const T,
}
```
I'd naively assume the field `pointer: *mut T`. Could this be the reason why `miri` is reporting this or should this be fine still?

**Comment by RalfJung** [comment] 2024-01-23 12:59
It seems like the original issue is resolved. It's also a duplicate of https://github.com/rust-lang/miri/issues/3243. So I'll close this issue.

For the pointer error you are getting, the problem is that somewhere you are turning a shared reference into a raw pointer and later that raw pointer into a mutable reference. The internal definition of `NonNull` is not a problem. Please file a new issue describing your question, or ask [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/269128-miri).

**Closed by RalfJung** 2024-01-23 12:59 UTC

**Comment by Robbepop** [comment] 2024-01-23 13:02
Okay thanks and sorry about the follow-up!

**Comment by RalfJung** [comment] 2024-01-23 14:11
No worries. With so many communication channels things can be quite confusing. :)

Opening issues for "why does Miri reject this code" is fine, but things are less confusing when we keep issues to "one question per issue".
