### ISSUE TITLE
Implement libstd HashMap seeding on OS X

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#686] opened 2019-04-11 21:19 UTC
PR https://github.com/rust-lang/miri/pull/683 implemented support for random number generation on Windows and (relatively recent) Linux. This was accomplished by implementing `RtlGenRandom` and `getrandom` for Windows and Linux respectively.

For OS X (and other Unix systems without `getrandom`), implementing random number generation is significantly more complicated. We need to implement the following:

* Calling `open`/`openat` with `/dev/random` and `/dev/urandom`
* Calling `read` and `close` on the 'file descriptor' created above.

On Linux, file descriptors appear to be assigned sequentially. However, I don't believe that anything actually guarantees this - in other words, this could potentially be considered a source of non-determinism.

**Comment by RalfJung** [comment] 2019-04-12 09:47
Uh, yes, this will be awful.

Alternatively we could "just" grant the interpreter FS access.  But of course that would break cross-execution.

**Comment by oli-obk** [comment] 2019-04-12 16:34
In order to keep file descriptors deterministic, we can use "symbolic file descriptors" (generate a new `AllocId` on every `open` call)

**Comment by RalfJung** [comment] 2019-04-12 17:08
What is the point, if we allow programs to open and read files they are not deterministic any more anyway?

For a given seed, we'll always assign the same file descriptors.  Small changes elsewhere in the program might affect that, but the same is true for the non-determinism that we return.

**Comment by Aaron1011** [comment] 2019-04-13 05:50
This is actually going to be really simple once https://github.com/rust-lang/rust/pull/59879 is merged, since `SecRandomCopyBytes` is essentially the same as all of the other random-generating functions.

**Comment by etaoins** [comment] 2019-04-17 11:55
@Aaron1011 

Assuming there are no other open file descriptors the sequential allocation is [guaranteed by POSIX](http://pubs.opengroup.org/onlinepubs/009695399/functions/open.html):
> The open() function shall return a file descriptor for the named file that is the lowest file descriptor not currently open for that process.

**Comment by uberjay** [comment] 2019-04-17 21:42
> This is actually going to be really simple once [rust-lang/rust#59879](https://github.com/rust-lang/rust/pull/59879) is merged, since `SecRandomCopyBytes` is essentially the same as all of the other random-generating functions.

Unfortunately it turns out that `SecRandomCopyBytes` was not such a great solution after all: https://github.com/rust-lang/rust/pull/59879#issuecomment-482938583. :(

**Comment by RalfJung** [comment] 2019-04-18 13:02
Dang. :/

There is no precedent for this, but in principle we could also patch libstd to use the `miri` config flag as an indication to follow the iOS code path. Then we could still rely on `SecRandomCopyBytes`.

**Comment by oli-obk** [comment] 2019-04-19 07:58
I think for a bunch of these APIs we should not reproduce the platform APIs, but add some attributes to a high level function that all platforms go through and hook miri into that.

**Comment by RalfJung** [comment] 2019-04-21 19:33
Actually, for the `rand` crate, `SecRandomCopyBytes` is being used (through https://github.com/rust-random/getrandom/blob/master/src/macos.rs). So implementing that would still help.

**Comment by RalfJung** [comment] 2019-04-21 21:17
See https://github.com/rust-lang/miri/pull/709 and https://github.com/rust-lang/rust/pull/60156

**Comment by RalfJung** [comment] 2019-06-29 11:05
Status update: libstd is moving to using the `getrandom` crate for seeding HashMap. That would unify that code path with what the rand crate uses. Currently `getrandom` works on macOS in Miri because they use `SecRandomCopyBytes`, but that has been causing problems and they are [still discussing what to do on macOS](https://github.com/rust-lang/miri/issues/800).

**Comment by RalfJung** [comment] 2019-06-29 11:07
The current plan for `getrandom` seems to be to use the `getentropy` syscall, loaded via `dlsym`. So if we could adapt @oli-obk's hack for getting `dlsym` function pointers to work in Miri, that should actually work. :)

**Comment by RalfJung** [comment] 2019-07-16 16:02
Current status: should be fixed by https://github.com/rust-lang/rust/pull/62082.

**Closed** 2019-12-31 11:38 UTC
Labels: A-mac, A-shims, C-enhancement
