### ISSUE TITLE
Stack traces on data races

### ISSUE THREAD

**Issue by fakedrake** [rust-lang/miri#2637] opened 2022-10-29 17:05 UTC
I am having a hard time debugging a problem that miri is reporting. It says `Data race detected between Atomic RMW on thread 'thread-2' and Write on thread 'thread-3' at alloc3257278` and proceeds to give me a stack trace at an atomic increment location (`thread-2` presumably). The problem is that this this variable is never written to outside of the atomic operations. Is there a way to get any information about the write operation on `thread-2`?

**Comment by saethlin** [comment] 2022-10-29 19:10
It's up to you whether you consider this a duplicate of https://github.com/rust-lang/miri/issues/2205

I'm on the fence because it sounds to me like you'd be happy with just something like `-Zmiri-track-alloc-id` for printing all accesses? It would be a colossal amount of data but maybe you could filter it down with `grep` or something?

**Comment by fakedrake** [comment] 2022-10-29 19:12
Thanks! It's not ideal but it might work
________________________________

**Comment by RalfJung** [comment] 2022-10-30 09:30
Yeah I'd say this is a duplicate of https://github.com/rust-lang/miri/issues/2205.

**Closed by RalfJung** 2022-10-30 09:30 UTC
