### ISSUE TITLE
hashbrown try_reserve test fails under miri

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/miri#655] opened 2019-03-07 18:17 UTC
It seems that miri fails when someone tries to allocate too much memory, instead of returning an error. I'll try to minimize this.

**Comment by gnzlbg** [comment] 2019-03-07 18:25
MWE ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=33c59c07e9c2c6fefc28aeea2da154d0)):

```rust
fn main() {
    let layout = std::alloc::Layout::from_size_align(usize::max_value(), 1).unwrap();
    let ptr: *mut u8 = unsafe { std::alloc::alloc(layout) };
    assert!(ptr.is_null());
}
```

fails with: 

```
memory allocation of 18446744073709551615 bytes failed
```

**Comment by RalfJung** [comment] 2019-03-08 08:47
Looks like a duplicate of https://github.com/rust-lang/miri/issues/613 ? If yes, please close this.

**Comment by RalfJung** [comment] 2019-03-08 12:25
(Closing for now, we can always reopen.)

**Closed by RalfJung** 2019-03-08 12:25 UTC
