### ISSUE TITLE
-Zmiri-seed doesn't work on macOS

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/miri#842] opened 2019-07-16 14:43 UTC
Running the following on macOS with `cargo miri test -- -Zmiri-seed=23`
```rust
        let mut h = std::collections::hash_map::HashMap::new();
        h.insert("Foo".to_string(), 4);
```

gives:
```
error[E0080]: Miri evaluation error: can't call foreign function: open
   --> /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/fs.rs:465:13
    |
465 |             open64(path.as_ptr(), flags, opts.mode as c_int)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: can't call foreign function: open
    |
    = note: inside call to closure at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/mod.rs:140:19
    = note: inside call to `std::sys::unix::cvt_r::<i32, [closure@DefId(1:8451 ~ std[797b]::sys[0]::unix[0]::fs[0]::{{impl}}[13]::open_c[0]::{{closure}}[0]) 0:&&std::ffi::CStr, 1:&i32, 2:&&std::sys::unix::fs::OpenOptions]>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/fs.rs:464:18
    = note: inside call to `std::sys::unix::fs::File::open_c` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/fs.rs:456:9
    = note: inside call to `std::sys::unix::fs::File::open` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/fs.rs:906:9
    = note: inside call to `std::fs::OpenOptions::_open` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/fs.rs:902:9
    = note: inside call to `std::fs::OpenOptions::open::<&std::path::Path>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/fs.rs:370:9
    = note: inside call to `std::fs::File::open::<&str>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/rand.rs:85:24
    = note: inside call to `std::sys::unix::rand::imp::fill_bytes` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/rand.rs:9:9
    = note: inside call to `std::sys::unix::rand::hashmap_random_keys` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs:2449:23
    = note: inside call to `std::collections::hash_map::RandomState::new::KEYS::__init` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:231:5
    = note: inside call to `<fn() -> std::cell::Cell<(u64, u64)> {std::collections::hash_map::RandomState::new::KEYS::__init} as std::ops::FnOnce<()>>::call_once - shim(fn() -> std::cell::Cell<(u64, u64)> {std::collections::hash_map::RandomState::new::KEYS::__init})` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:285:25
    = note: inside call to `std::thread::local::lazy::LazyKeyInner::<std::cell::Cell<(u64, u64)>>::initialize::<fn() -> std::cell::Cell<(u64, u64)> {std::collections::hash_map::RandomState::new::KEYS::__init}>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:426:22
    = note: inside call to `std::thread::__FastLocalKeyInner::<std::cell::Cell<(u64, u64)>>::try_initialize::<fn() -> std::cell::Cell<(u64, u64)> {std::collections::hash_map::RandomState::new::KEYS::__init}>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:411:25
    = note: inside call to `std::thread::__FastLocalKeyInner::<std::cell::Cell<(u64, u64)>>::get::<fn() -> std::cell::Cell<(u64, u64)> {std::collections::hash_map::RandomState::new::KEYS::__init}>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:176:17
    = note: inside call to `std::collections::hash_map::RandomState::new::KEYS::__getit` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:254:32
    = note: inside call to `std::thread::LocalKey::<std::cell::Cell<(u64, u64)>>::try_with::<[closure@DefId(1:1022 ~ std[797b]::collections[0]::hash[0]::map[0]::{{impl}}[66]::new[0]::{{closure}}[0])], std::collections::hash_map::RandomState>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:234:9
    = note: inside call to `std::thread::LocalKey::<std::cell::Cell<(u64, u64)>>::with::<[closure@DefId(1:1022 ~ std[797b]::collections[0]::hash[0]::map[0]::{{impl}}[66]::new[0]::{{closure}}[0])], std::collections::hash_map::RandomState>` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs:2452:9
    = note: inside call to `std::collections::hash_map::RandomState::new` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs:2525:9
    = note: inside call to `<std::collections::hash_map::RandomState as std::default::Default>::default` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs:1021:30
    = note: inside call to `<std::collections::HashMap<std::string::String, i32> as std::default::Default>::default` at /Users/jrmuizel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs:226:9
note: inside call to `std::collections::HashMap::<std::string::String, i32>::new` at src/lib.rs:5:21
   --> src/lib.rs:5:21
    |
5   |         let mut h = std::collections::hash_map::HashMap::new();
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RalfJung** [comment] 2019-07-16 15:59
`HashMap` is unfortunately not supported on macOS currently. This should be fixed eventually when https://github.com/rust-lang/miri/issues/686 lands.

Closing as duplicate of https://github.com/rust-lang/miri/issues/686.

**Closed by RalfJung** 2019-07-16 15:59 UTC
