### ISSUE TITLE
teach miri to use intrinsics' fallback bodies

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#3397] opened 2024-03-23 10:37 UTC
And then replace lots of our SIMD and numeric  shims with fallback bodies by adding said fallback bodies to libcore.

Note that we need to take lots of care to preserve UB.

This may regress diagnostics quality, so maybe we need some sort of `unreachable_unchecked` intrinsic equivalent which can be passed a string that explains the UB?

**Comment by RalfJung** [comment] 2024-03-23 10:39
I think we may want to require some sort of opt-in here, like `#[rustc_intrinsic_fallback_fit_for_miri]` or so, so that one can locally review in the intrinsic body whether the requirement is upheld.

**Comment by RalfJung** [comment] 2024-05-03 17:45
Isn't this a duplicate of https://github.com/rust-lang/miri/issues/3302?

**Closed** 2024-05-04 14:49 UTC
Labels: C-cleanup, A-intrinsics
