### ISSUE TITLE
`cargo miri test` fails without `RUSTC` env var

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/miri#3775] opened 2024-07-30 09:31 UTC
```console
> cargo miri test
thread 'main' panicked at src/tools/miri/cargo-miri/src/setup.rs:103:13:
assertion failed: env::var_os("RUSTC").is_some()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7c2012d0ec3aae89fefc40e5d6b317a0949cda36/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/7c2012d0ec3aae89fefc40e5d6b317a0949cda36/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/7c2012d0ec3aae89fefc40e5d6b317a0949cda36/library/core/src/panicking.rs:148:5
   3: cargo_miri::phases::phase_cargo_miri::<std::env::Args>
   4: cargo_miri::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

for some reason I'm forced to explicitly tell miri that yes, rustc is rustc, which it then promptly ignores

```console
> RUSTC=rustc cargo miri test
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
WARNING: Ignoring `RUSTC` environment variable; set `MIRI` if you want to control the binary used as the driver.
...
```

**Comment by RalfJung** [comment] 2024-07-30 10:09
This assertion you are hitting is only active when `RUSTC_STAGE` is set. That environment variable should *never be set* outside of rustc bootstrap. Any idea why it is set in your environment?

**Comment by Nemo157** [comment] 2024-07-30 13:45
Ah right, I do some strange things to try and avoid failures from nightly-detecting crates

```sh
# Some crates disable nightly feature detection when this is set
export RUSTC_STAGE=1
```

I guess I might need a `cargo-miri` wrapper that unsets that then :thinking:

**Comment by RalfJung** [comment] 2024-07-30 14:59
Ah, damn, that is an unfortunate clash.

I'm going to close this issue since there's not a bug here (and https://github.com/rust-lang/rust/pull/128382 will make the error a bit less confusing). If you have ideas for how else Miri could detect that it runs inside bootstrap then please let us know.

**Closed by RalfJung** 2024-07-30 14:59 UTC
