### ISSUE TITLE
macosx

### ISSUE THREAD

**Issue by jayhill365** [rust-lang/miri#1946] opened 2021-12-20 21:16 UTC
this doesn't work on macos, fails to properly build, any pointers here would be appreciated

**Comment by oli-obk** [comment] 2021-12-20 21:32
Can you share some info on the build failure? We can't really help you debug otherwise.

Pointers for helping to build would be, lacking further info, to read the getting started instructions

**Comment by RalfJung** [comment] 2021-12-20 21:39
I assume this is a duplicate of https://github.com/rust-lang/miri/issues/1941.

But indeed, please remember to *always* copy the full error message when reporting an error. Developers are (typically) not psychic :)

**Comment by RalfJung** [comment] 2021-12-21 08:52
Closing as duplicate of https://github.com/rust-lang/miri/issues/1941

**Closed by RalfJung** 2021-12-21 08:52 UTC

**Comment by jayhill365** [comment] 2021-12-22 02:21
<img width="941" alt="Screen Shot 2021-12-21 at 6 21 07 PM" src="https://user-images.githubusercontent.com/19259608/147024148-617f12f7-c879-4444-ac50-058298a75a27.png">
